name: Build and Release
on:
  push:
    tags:
      - 'v*'
permissions:
    contents: write
    packages: write
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.21'

        - name: Build binary
          run: |
            go build -o gdm

        - name: Create GitHub Release
          uses: softprops/action-gh-release@v2
          with:
            files: gdm
